### ISSUE TITLE
[Feat] 디자인 수정으로 인한 메인 페이지 개발

### ISSUE THREAD

**Issue by yh-project** [99z-diary/99z-diary-web-fe#17]
## 📔 Description
- 상단 네비게이션 바 수정
- 메인 페이지 개발

## 🐈 Todo

- [x] 상단 네비게이션 바 수정
- [x] 메인 페이지 로그인 컴포넌트 개발
- [x] 메인 페이지 그룹 리스트 컴포넌트 개발
